0 ./summa.exe -g 1 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
1 ./summa.exe -g 2 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
2 ./summa.exe -g 3 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
3 ./summa.exe -g 4 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
4 ./summa.exe -g 5 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
5 ./summa.exe -g 6 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
6 ./summa.exe -g 7 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
7 ./summa.exe -g 8 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
8 ./summa.exe -g 9 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
9 ./summa.exe -g 10 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
10 ./summa.exe -g 11 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
11 ./summa.exe -g 12 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
12 ./summa.exe -g 13 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
13 ./summa.exe -g 14 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
14 ./summa.exe -g 15 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
15 ./summa.exe -g 16 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
16 ./summa.exe -g 17 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
17 ./summa.exe -g 18 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
18 ./summa.exe -g 19 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
19 ./summa.exe -g 20 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
20 ./summa.exe -g 21 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
21 ./summa.exe -g 22 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
22 ./summa.exe -g 23 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
23 ./summa.exe -g 24 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
24 ./summa.exe -g 25 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
25 ./summa.exe -g 26 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
26 ./summa.exe -g 27 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
27 ./summa.exe -g 28 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
28 ./summa.exe -g 29 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
29 ./summa.exe -g 30 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
30 ./summa.exe -g 31 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
31 ./summa.exe -g 32 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
32 ./summa.exe -g 33 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
33 ./summa.exe -g 34 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
34 ./summa.exe -g 35 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
35 ./summa.exe -g 36 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
36 ./summa.exe -g 37 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
37 ./summa.exe -g 38 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
38 ./summa.exe -g 39 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
39 ./summa.exe -g 40 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
40 ./summa.exe -g 41 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
41 ./summa.exe -g 42 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
42 ./summa.exe -g 43 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
43 ./summa.exe -g 44 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
44 ./summa.exe -g 45 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
45 ./summa.exe -g 46 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
46 ./summa.exe -g 47 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
47 ./summa.exe -g 48 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
48 ./summa.exe -g 49 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
49 ./summa.exe -g 50 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
50 ./summa.exe -g 51 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
51 ./summa.exe -g 52 1 -r never -m /scratch/csun15/calib/summa_calib/CAN_05BB001/model/settings/SUMMA/fileManager.txt
